### ISSUE TITLE
当前主题看着很舒服,希望把侧栏固定住,或者增加一个返回顶部功能

### ISSUE THREAD

**Issue by markerui** [wangdoc/loppo-theme-wangdoc#1]
有些文章实在太长了。第二次来刷的时候，可能只是快速找下使用。经常看着看着就滚动了很长的滚动条
希望考虑把侧栏永远固定在右侧，或者增加一个返回顶部功能。方便快速切换栏目

**Comment by markerui** [comment]
哈哈哈。。。我鼠标放到标题上，原来有个返回顶部功能。。我大意了～～～赞赞赞

**Comment by ruanyf** [comment]
侧栏如果固定下来，就会有一个滚动条，等于右侧有两个滚动条。所以，目前的主题不太好固定。

以后改主题的时候，会考虑。
